name: Build and push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: java-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DOCKERHUB

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Secret
        run: |
            if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "Secret missing"
            exit 1
            fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v4.2.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7.2.0
        with:
          context: .
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
